config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'posts/index'
  get 'posts/edit'
  get 'posts/show'
  get 'sessions/new'
  get 'users/index'
  get 'users/edit'
  get 'users/new'
  get 'users/show'
  get('/',{to: "posts#index", as: :home})

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    get 'edit_password', to: 'users#edit_password', as: 'edit_password'
    patch 'update_password', to: 'users#update_password', as: 'update_password'
  end


  resources :sessions, only: [:new, :destroy, :create]
   
  root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new # guest user (not logged in)
    #  if user.admin?
    #    can :manage, :all
    #  else
    #    can :read, :all
    #  end
  
    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Post do |post|
      user == post.user
    end   

    can :crud, Comment do |comment|
      user == comment.user
    end

    can :crud, User, id: user.id

     
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, length: {minimum:3, maximum:200}
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :title, presence: { message: "title must be provided" }, uniqueness: true
    validates :body, presence: true, length: { minimum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    
     


    def full_name
        self.first_name + " " + self.last_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!       
        if !user_signed_in?
            flash.notice = "Please sign in first!"
            redirect_to sessions_new_path
        end
    end    

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?
        
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  
  def create
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post;
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post.id), status: 303
    else
      @comments = @post.comments
      render '/posts/show', status: 303
    end    
  end

  def destroy
    @comment = Comment.find params[:id]
    @post = @comment.post

    if can?(:crud, @comment)
      @comment.destroy
      redirect_to post_path(@post)
    else
      redirect_to root_path, alert: "Not Authorized"
    end

  end
  
  private

  def find_post
    @post = Post.find params[:post_id]
  end    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_user!, only:[:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
   @post = Post.new(post_params)
   @post.user = current_user
   if @post.save
     flash.notice = "Post created successfully!"
     redirect_to post_path(@post.id)
   else
     render :new, status: 303
   end   
  end

  def index
    @posts = Post.order(created_at: :desc)    
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: 303
    end
  end

  def show
    @post = Post.find params[:id]
    @comments = @post.comments
    @comment = Comment.new
  end

  def destroy
    @post.destroy
    redirect_to posts_index_path
  end

  private

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless can?(:crud, @post)
  end  

  def find_post
    @post = Post.find params[:id]
  end  

  def post_params
    params.require(:post).permit(:title, :body)  
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
        
  end

  def create
     @user = User.find_by_email params[:email]
  
     if @user && @user.authenticate(params[:password])
       session[:user_id] = @user.id
       # flash.notice = "Logged in" # or ↓↓↓
       redirect_to root_path, {notice: "Logged in"}
     else
       render :new, { alert: "Wrong email or password!", status: 303 }
     end
  end

  def destroy
    session[:user_id] = nil
    flash.notice = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :edit_password, :update_password]
  before_action :find_user, only: [:edit, :update]
  before_action :authorize!, only: [:edit, :update]
  
  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update user_params
      flash[notice] = 'Updated Successfully'
      redirect_to root_path
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new params.require(:user).permit(
         :first_name,:last_name,:email,:password,:password_confirmation
     )
     if @user.save
         session[:user_id] = @user.id
         flash.notice = "Logged in!"
         redirect_to root_path
     else
         render :new, status: 303
     end
  end

  def show
  end


  def edit_password
        @user = User.find params[:user_id]
        authorize!
    end

  def update_password
    @user = User.find params[:user_id]
    if @user&.authenticate params[:user][:current_password]
      new_password = params[:user][:new_password]
      new_password_confirmation = params[:user][:new_password_confirmation]
      new_password_different = new_password != params[:user][:current_password]
      password_confirmed = new_password == new_password_confirmation

      if new_password_different && password_confirmed
        if  @user.update password: new_password, password_confirmation: new_password_confirmation
          flash[:notice] = "Password changed successfully!"
          redirect_to root_path, status: 303
        else
          flash[:alert] = "Password update fail"
          render :edit_password, status: 303
        end
      else
        flash[:alert] = "New password confirmation does not match."
        render :edit_password, status: 303
      end
    else
      flash[:alert] = "Your current password does not match our records"
      render :edit_password, status: 303
    end 

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end  
  
  def find_user
    @user = User.find params[:id]
  end

  def authorize!
    unless can? :crud, @user
    redirect_to root_path 
    flash[:alert] =  'Access Denied'
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'navigation' %>
  <hr />
     <nav>
      <%= link_to 'Posts Index Page', posts_path %>
      <%= link_to 'New Post Page', posts_new_path%>
    </nav>

    <%if(user_signed_in?) %>
    <% session[:user_id] = current_user.id %>
      <h2>Hello <%= link_to "#{current_user.full_name}", edit_user_path(current_user) %></h2>
      <%= button_to "Log out", session_path(:user_id), method: :delete %>
    <% else %>
      <%= link_to 'Sign In Page', sessions_new_path%>
      <%= link_to 'Sign Up Page', new_user_path%>
    <% end %>

   <% flash.each do |type, message| %>
      <%= type + "-------" + message %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <a class="nav-link navbar-brand" aria-current="page" href="<%= home_path %>">BlogOnRails</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= home_path %>">Home</a>
        </li>

 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Posts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if(user_signed_in?)  %>
            <%= link_to "Create New Post", posts_new_path, class: "dropdown-item" %>
          <% else %>  
             <%= link_to "Sign In", sessions_new_path, class: "dropdown-item" %>
             <%= link_to "Sign Up", new_user_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View Posts", home_path, class: "dropdown-item" %>
            <%# <li><hr class="dropdown-divider"></li> %>
            <%# <li><a class="dropdown-item" href="#">Something else here</a></li> %>
          </ul>
        </li>

        <li class="nav-item">
           <% if(user_signed_in?) %>
            <a class="nav-link" href="<%= edit_user_path(current_user.id) %>">Current User: <%= current_user.full_name %></a>
           <% end %> 
        </li>

 

        <li class="nav-item">
          <% if(user_signed_in?) %>
            <% session[:user_id] = current_user.id %>
            
            <%= button_to "Log out", session_path(:user_id), class:"nav-link btn btn-outline-info", method: :delete %>
          <% else %>  
            <li class="nav-item" style="margin-right: 10px;"><a class="nav-link btn btn-outline-info btn-sm" href="<%= sessions_new_path %>"> Sign In Page</a></li>
            <li class="nav-item"><a class="nav-link btn btn-outline-info btn-sm" href="<%= new_user_path %>"> Sign Up Page</a></li>
          <% end %>
        </li>

 
 

      </ul>
    </div>
  </div>
</nav>

  <hr />
 

 

   <% flash.each do |type, message| %>
      <%= type + "-------" + message %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>
<%= form_with(model: @post, url: posts_path ) do |form| %>
    <div>
        <%= form.label :title %>
        <br>
        <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div>
        <%= form.label :body %>
        <br>
        <%= form.text_area :body, class: 'form-control' ,cols: 50, rows: 5 %>
    </div>
    <div class="mt-2">
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="text-center">Post Edit Page</h1>
<div class="container">
    <% if @post.errors.any? %>
        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
        </ul>
    <% end %>
    <%= form_with(model: @post, url: post_path, method: :patch ) do |form| %>
        <div>
            <%= form.label :title %>
            <br>
            <%= form.text_field(:title, :style => "width:1303px;")  %>
        </div>
        <div>
            <%= form.label :body %>
            <br>
            <%= form.text_area :body, cols: 152, rows: 5 %>
        </div>
        <%= form.submit %>
    <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="text-center">Post Home Page</h1>
<div class="container text-center">
<% @posts.each do |post| %>
    <div>
        <p><%= link_to post.title, post_path(post.id)  %></p>
    </div>    
<% end %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">New Post Page</h1>
<div class="container"> 

    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<h1 class="text-center">Post Show Page</h1>
<div class="container ">
<h2><%= @post.title %></h2>
<p>
    <span><%= @post.body %></span>
   
</p>
<p>
    <small>Created at: <%= @post.created_at %></small>
    <small>- By: <%= @post.user.full_name%></small>
    <% if can? :crud, @post %>
        <div class="d-flex">
            <span><%= button_to 'Edit', edit_post_path(@post), method: :get %></span>
            <span><%= button_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %></span>
        </div>    
    <% end %>  
</p>



<h4>Comments</h4>

<ul class="list-group">
    <% @comments.each do |comment| %>
        <li class="list-group-item">
            <%= comment.body%>
            <p>
                <small>Commented <%= time_ago_in_words(comment.created_at) %> ago </small>
                <small> - By: <%= comment.user.full_name%> </small>
             
                <% if can? :crud, comment %>
                    <%= button_to "Delete", post_comment_path(@post.id, comment.id), method: :delete %>
                <% end %>
            </p>
        </li>
    <% end %>
</ul>

<hr>

<h4>Write your comment</h4>

<% if @comment.errors.any? %>
    <ul>
        <% @comment.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>
<%= form_with(model:[@post, @comment]) do |f|%>

    <div>
        <%= f.label :body%>
        <br>        
        <%= f.text_area :body, class: 'form-control', cols:100, rows:5 %>
    </div>

    <%= f.submit "Add Comment" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit User Profile</h1>
<div>
<% if @user.errors.any? %>
    <p><%= @user.errors.full_messages.join(', ') %> </p>
<% end %>
<%= form_with model: @user do |f| %>
    <div>
        <%= f.label :first_name%>
        <%= f.text_field :first_name%>
    </div>
    <div>
        <%= f.label :last_name%>
        <%= f.text_field :last_name%>
    </div>
    <div>
        <%= f.label :email%>
        <%= f.text_field :email%>
    </div>
    <%= f.submit "Update" %>
<% end %>
<%= link_to 'Change Password', user_edit_password_path(@user.id) %>

app/views/users/edit_password.html.erb
<h1 class="text-center">Change Password</h1>
<div class="container">
    <%= form_with model: @user, url: user_update_password_path(@user.id), local: true do |f| %>
        <% if @user.errors.any? %>
            <p><%= @user.errors.full_messages.join(', ') %> </p>
        <% end %>
        <div>
            <div>
                <div class="mb-3">
                    <%= f.label :current_password, "Current Password", { class: "form-label" } %>
                    <%= f.password_field :current_password, { class: "form-control", placeholder: "Old password" } %>
                </div>
                <div class="mb-3">
                    <%= f.label :new_password, "New Password", { class: "form-label" } %>
                    <%= f.password_field :new_password, { class: "form-control", placeholder: "New password" } %>
                </div>
                <%= f.label :new_password_confirmation, "New Password Confirmation", { class: "form-label" } %>
                        <%= f.password_field :new_password_confirmation, { class: "form-control", placeholder: "Confirm New password" } %>
            </div>
        </div>
        <div class="mb-3 mt-3">
            <%= f.submit "Update Password", class: "btn btn-outline-info btn-lg" %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">

    <%= form_with( model: @user , class: "shadow p-3 mb-3 bg-info rounded")do |f|%>
      <% if @user.errors.any? %>
        <p><%= @user.errors.full_messages.join(', ') %> </p>
      <% end %>
        <div class="form-group row">
            <%= f.label :first_name%>
            <%= f.text_field :first_name%>
        </div>
        <div class="form-group row">
            <%= f.label :last_name%>
            <%= f.text_field :last_name%>
        </div>
        <div class="form-group row">
            <%= f.label :email%>
            <%= f.text_field :email%>
        </div>
        <div class="form-group row">
            <%= f.label :password%>
            <%= f.text_field :password%>
        </div>
        <div class="form-group row">
            <%= f.label :password_confirmation%>
            <%= f.text_field :password_confirmation%>
        </div>
        <div class="form-group row justify-content-center p-4">
          <%= f.submit "Sign Up", class: "btn btn-outline-light btn-lg" %>
        </div>
    <% end %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>